baseURL = "https://pet.informationhot.kr/"
languageCode = "ko"
title = "반려동물용품 추천 가이드"
theme = "blowfish"
defaultContentLanguage = "ko"
enableRobotsTXT = true

[pagination]
  pagerSize = 12
summaryLength = 150

[outputs]
  home = ["HTML", "RSS", "JSON"]

[sitemap]
  changefreq = "daily"
  priority = 0.5

[taxonomies]
  tag = "tags"
  category = "categories"


[related]
  threshold = 0
  toLower = false

  [[related.indices]]
    name = "tags"
    weight = 100

  [[related.indices]]
    name = "categories"
    weight = 100

  [[related.indices]]
    name = "series"
    weight = 50

  [[related.indices]]
    name = "date"
    weight = 10
timeZone = "Asia/Seoul"
themesDir = "/Users/twinssn/Projects/shared-themes"
