googleAnalytics = "G-SXMKNQS134"
defaultBackgroundImage = "/img/background.svg"

colorScheme = "ocean"
defaultAppearance = "light"
autoSwitchAppearance = false
enableSearch = true
enableCodeCopy = false

[header]
  layout = "basic"
  showTitle = true

[footer]
  showCopyright = true
  showThemeAttribution = false
  showScrollToTop = true

[homepage]
  layout = "profile"
  showRecent = true
  showRecentItems = 12
  showMoreLink = true
  showMoreLinkDest = "/posts"
  cardView = false

[article]
  showDate = true
  showDateUpdated = false
  showAuthor = false
  showBreadcrumbs = true
  showReadingTime = true
  showTableOfContents = false
  showRelatedContent = false
  relatedContentLimit = 5
  showTaxonomies = true
  showWordCount = false
  showComments = false
  showHero = true
  heroStyle = "basic"

[list]
  showBreadcrumbs = true
  showSummary = true
  showCards = true
  groupByYear = false

[taxonomy]
  showTermCount = true
  showBreadcrumbs = true


[advertisement]
  adsense = "ca-pub-6677996696534146"
  inArticleSlot = "2195212287"
  topSlot = "2195212287"
