name = "pet-hugo"
compatibility_date = "2025-07-31"

routes = [
  { pattern = "pet.informationhot.kr/*", zone_name = "informationhot.kr" }
]

[assets]
directory = "./public"
not_found_handling = "404-page"
html_handling = "auto-trailing-slash"
